# Generated by Django 3.0.8 on 2020-07-15 10:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riskAssesment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_date', models.DateField(blank=True, default=datetime.date(2020, 7, 15))),
                ('status', models.CharField(blank=True, max_length=250)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('Screening', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='riskAssesment.Screening')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
